# chromium
# Autogenerated from man page /usr/share/man/man1/chromium.1.gz
complete -c chromium -l user-data-dir -d 'Specifies the directory that user data (your "profile") is kept in'
complete -c chromium -l incognito -d 'Open in incognito mode'
complete -c chromium -l new-window -d 'If PATH or URL is given, open it in a new window'
complete -c chromium -l proxy-server -d 'Specify the HTTP/SOCKS4/SOCKS5 proxy server to use for requests'
complete -c chromium -l no-proxy-server -d 'Disables the proxy server'
complete -c chromium -l proxy-auto-detect -d 'Autodetect proxy configuration'
complete -c chromium -l proxy-pac-url -d 'Specify proxy autoconfiguration URL'
complete -c chromium -l password-store -d 'Set the password store to use'
complete -c chromium -l version -d 'Show version information'
complete -c chromium -l display -d 'See the GTK documentation for more: <http://library. gnome'

