# lua5
# Autogenerated from man page /usr/share/man/man1/lua5.3.1.gz
complete -c lua5 -s e -d 'execute statement R stat '
complete -c lua5 -s i -d 'enter interactive mode after executing R script '
complete -c lua5 -s l -d 'execute the equivalent of B name =require(\' name \') before executing R script '
complete -c lua5 -s v -d 'show version information'
complete -c lua5 -s E -d 'ignore environment variables'

