# plasmoidviewer
# Autogenerated from man page /usr/share/man/man1/plasmoidviewer.1.gz
complete -c plasmoidviewer -s v -l version -d 'Displays version information'
complete -c plasmoidviewer -s c -l containment -d 'The name of the containment plugin'
complete -c plasmoidviewer -s a -l applet -d 'The name of the applet plugin'
complete -c plasmoidviewer -s f -l formfactor -d 'The formfactor to use (horizontal, vertical, mediacenter, planar or applicati…'
complete -c plasmoidviewer -s l -l location -d 'The location constraint to start the Containment with (floating, desktop, ful…'
complete -c plasmoidviewer -s x -l xPosition -d 'Set the x position of the plasmoidviewer on the Plasma desktop'
complete -c plasmoidviewer -s y -l yPosition -d 'Set the y position of the plasmoidviewer on the Plasma desktop'
complete -c plasmoidviewer -s s -l size -d 'Set the window size of the plasmoidview'
complete -c plasmoidviewer -s p -l pixmapcache -d 'The size in KB to set the pixmap cache to'
complete -c plasmoidviewer -s t -l theme -d 'The name of the theme which the shell will use'
complete -c plasmoidviewer -s h -l help -d 'Displays this help'

