# plasmaengineexplorer
# Autogenerated from man page /usr/share/man/man1/plasmaengineexplorer.1.gz
complete -c plasmaengineexplorer -s v -l version -d 'Displays version information'
complete -c plasmaengineexplorer -s h -l help -d 'Displays this help'
complete -c plasmaengineexplorer -l list -d 'Displays a list of known engines and their descriptions'
complete -c plasmaengineexplorer -l height -d 'Sets the height of the window, in pixels'
complete -c plasmaengineexplorer -l width -d 'Sets the width of the window, in pixels'
complete -c plasmaengineexplorer -s x -d 'Sets the x (horizontal) co-ordinate of the top left corner of the window, in …'
complete -c plasmaengineexplorer -s y -d 'Sets the y (vertical) co-ordinate of the top left corner of the window, in pi…'
complete -c plasmaengineexplorer -l engine -d 'Start plasmaengineexplorer with the given data engine selected'
complete -c plasmaengineexplorer -l source -d 'Only valid in conjunction with --engine'
complete -c plasmaengineexplorer -l interval -d 'Sets the default update interval for requested sources to time milliseconds'
complete -c plasmaengineexplorer -l app -d 'Only show engines associated with the parent application; maps to the X-KDE-P…'

