// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "f353549e-0410-48de-9889-639573ecff2b");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1653126205);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1653126248);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1653126280);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1653126306);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1653126234);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "strict");
user_pref("browser.contextual-services.contextId", "{6a7e4caf-208f-4265-ba31-bc6e6086d806}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1653126175);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 125);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.impressionId", "{fd9690c9-f58b-433b-a4fb-e40949629b18}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "google");
user_pref("browser.newtabpage.blocked", "{\"26UbzFJ7qT9/4DhodHKA1Q==\":1,\"4gPpjkxgZzXPVtuEoAL9Ig==\":1,\"eV8/WsSLxHadrTL1gAxhug==\":1}");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://google.com\",\"label\":\"@google\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1653126280);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1653126215779");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1653128006779");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1653126205090");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1653147805090");
user_pref("browser.search.region", "SG");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20220514192836");
user_pref("browser.startup.homepage_override.mstone", "100.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1653126279);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Bing");
user_pref("browser.urlbar.placeholderName.private", "Bing");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1653126292659");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "100.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "SG");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "ea40e7237b424ec9b743350489f39ba3");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1653126281);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20220514192836");
user_pref("extensions.lastAppVersion", "100.0.1");
user_pref("extensions.lastPlatformVersion", "100.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/theme");
user_pref("extensions.ui.locale.hidden", false);
user_pref("extensions.ui.sitepermission.hidden", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"426ec2f5-bf95-48da-8008-9b41c5eeb1c1\",\"formautofill@mozilla.org\":\"fde29dce-b298-4a05-8c8e-fa598e382b58\",\"pictureinpicture@mozilla.org\":\"96655f8b-d42f-40be-8ba4-463d3f5c9b8f\",\"screenshots@mozilla.org\":\"923d1fe2-efd1-4bf6-ac60-adec0cfb6227\",\"webcompat-reporter@mozilla.org\":\"0acdf9ef-4fd9-4889-98ec-7162fa39c89c\",\"webcompat@mozilla.org\":\"5e6e482c-1ffa-4aa4-b495-fc1118ded039\",\"default-theme@mozilla.org\":\"c072815b-e253-4ccb-bf3f-f32623c7c172\",\"addons-search-detection@mozilla.com\":\"25ad1e6d-3196-49b1-a115-e09b98231bd4\",\"google@search.mozilla.org\":\"e68eece4-880e-4e03-a498-6295e4e8c433\",\"wikipedia@search.mozilla.org\":\"8a3d26be-7b6a-411d-939c-a9167d1616ed\",\"baidu@search.mozilla.org\":\"dd9057e1-b214-4f74-83cd-e0e4cd9a476c\",\"bing@search.mozilla.org\":\"8b4aaa0f-1eab-41ca-b9eb-0cdcc8f33393\",\"ddg@search.mozilla.org\":\"45d0c969-d1f6-4296-8f78-25f7b64e3ea9\",\"firefox-alpenglow@mozilla.org\":\"75841002-89a3-48f9-83e5-ae4bae556945\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("layout.css.prefers-color-scheme.content-override", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.cookieBehavior", 5);
user_pref("network.cookie.lifetimePolicy", 2);
user_pref("network.http.referer.disallowCrossSiteRelaxingDefault.top_navigation", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.annotate_channels.strict_list.enabled", true);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.partition.network_state.ocsp_cache", true);
user_pref("privacy.restrict3rdpartystorage.rollout.enabledByDefault", false);
user_pref("privacy.restrict3rdpartystorage.rollout.preferences.TCPToggleInStandard", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.enabled", true);
user_pref("privacy.trackingprotection.socialtracking.enabled", true);
user_pref("security.sandbox.content.tempDirSuffix", "06b753f3-8816-450c-9409-a310a7aac242");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.engine.addresses.available", true);
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("toolkit.startup.last_success", 1653126271);
user_pref("toolkit.telemetry.cachedClientID", "ca92dc89-9090-4bcc-9914-6231a87372c5");
user_pref("toolkit.telemetry.previousBuildID", "20220514192836");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
